### PR TITLE
Fix fixtures folder.

### PR DESCRIPTION
**Pull request by fabianfiorotto**
When you run the tests of this package directly all tests pass but when you run them from the script `script/run-package-tests.js` from Atom/Pulsar the tests fail. That is because the project folder is not set correctly when there are other tests running along with these ones. If you set the project folder manually before each test then the tests pass always.

### CODE REVIEW

**Comment by confused-Techie** [comment]
This looks fantastic, but I'd like to go ahead and get our testing running on PR's before merging in if you don't mind.

**Review by mauricioszabo — APPROVED** [review]

**Comment by fabianfiorotto** [comment]
@confused-Techie I tried to put the current version of the code in Atom to run the test and it looks like it won't run. In [this commit](https://github.com/pulsar-edit/autocomplete-plus/commit/ed12ea79177ac7cac487f35f03144af8c6a6f977) the tests were changed to run in jasmine 3 which is not compatible with the version that comes with Atom. Should we revert that? ... since this is a core package it should support the same version as the rest of the editor.

**Comment by mauricioszabo** [comment]
YEAHHH, Atom uses a **very old** Jasmine version...

**Comment by mauricioszabo** [comment]
I vote for reverting, @fabianfiorotto

**Review by confused-Techie — APPROVED** [review]
Well either we could try bringing this version down or Pulsars up, And I'd vote more towards getting that one newer. But especially considering we might be moving to a new testing framework at one point its hard to say.

But knowing the test won't tell us anything lets get this merged and I'll approve.

**Comment by mauricioszabo** [comment]
@confused-Techie it's actually not that simple. Atom does not **depends on** a Jasmine framework, it **contains** the source of one, with some slight modifications.

Changing this file means we get an updated Jasmine, but have to keep this modified file updated (more code to maintain). It also means we break all tests that we have today, without exception (hurray for backwards compatibility, it would be so wonderful if at least **one** JavaScript library could have it...)

**Comment by confused-Techie** [comment]
> @confused-Techie it's actually not that simple. Atom does not **depends on** a Jasmine version, it **contains** the source of one, with some slight modifications.
> 
> Changing this file means we get an updated Jasmine, but have to keep this modified file updated (more code to maintain). It also means we break all tests that we have today, without exception (hurray for backwards compatibility, it would be so wonderful if at least **one** JavaScript library could have it...)

My lord is that horrendous. Okay so then yeah we gotta step this one down. And that means in the future to update our testing framework it'd be literally easier to scrape all tests, and rewrite from scratch in a framework that makes sense.

In that case lets hope that theres no big issues we introduce using an older testing framework.

So in that case hopefully we can revert this repos existing tests to whatever they had before the updated the framework

**Comment by confused-Techie** [comment]
So while we may not be able to test here, this PR is a bit old and looks like it has 2 approvals.

Just wanting to confirm that your approval is still accurate @mauricioszabo since I know I was the one saying it would be nice to test, and you had mentioned reverting the jasmine change.

Should we merge this and worry about reverting that change later on?

**Comment by mauricioszabo** [comment]
I missed this PR, sorry. Merging now :)

**Pull request merged**
